CREATE DATABASE IF NOT EXISTS url_shortener_db;

USE url_shortener_db;

CREATE TABLE IF NOT EXISTS url_shortener (
  id INT AUTO_INCREMENT PRIMARY KEY,
  original_url TEXT NOT NULL,
  short_code VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
